general:
  chat:
    channel:
      emote:
        pattern: '{Player} > {MSG}'
        range: 16
      say:
        pattern: '{Player} >> {MSG}'
        range: 32
      yell:
        pattern: '{Player} >>> {MSG}'
        range: 64
sql:
  host:
  port:
  database:
  user:
  password:
  players_table: players
  item_template: item_template
  quest_template: quest_template
  creature_template: creature_template
  loot_template: loot_template
  string_template: string_template