name: MMOCore
authors: [Arektor,Gendai,Mr_Freezeex]
version: 0.0.38
main: fr.tenebrae.MMOCore.Main
commands:
  me:
    description: emote channel
    usage: /me
  yell:
    description: yell channel
    usage: /yell
depend: [ProtocolLib]