name: tenebrae
main: fr.tenebrae.MMOCore.Main
version: 0.0.1
commands:
  spw:
    description: Spawn spider mine L01
    usage: /spw
  me:
    description: send chat message in emote channel
    usage: /me <msg>
  yell:
    description: send chat message in yell channel
    usage: /yell <msg>